port 1443
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA256
tls-crypt tc.key
topology subnet
server 10.253.1.0 255.255.255.0
push "block-ipv6"
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "route 10.1.1.0 255.255.255.0"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 9.9.9.9"
push "block-outside-dns"
client-to-client
keepalive 10 60
cipher AES-256-GCM
user nobody
group nogroup
persist-key
persist-tun
verb 3
crl-verify crl.pem
client-to-client

duplicate-cn
status /root/log/openvpn_server_tcp_status.log 10
status-version 2

log /root/log/openvpn_server_tcp.log
